name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    container:
      image: cypress/browsers:node-24.14.1-chrome-146.0.7680.164-1-ff-149.0-edge-146.0.3856.72-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress tests
        run: |
          npx cypress run \
          --browser ${{ matrix.browser }} \
          --key $CYPRESS_RECORD_KEY \
          --group "UI - ${{ matrix.browser }}" \
          --spec "${{ github.event.inputs.spec }}"

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
